// <auto-generated />
using System;
using EscaleraMillonaria_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EscaleraMillonaria_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211221151240_AddEscaleraMillonariaDB")]
    partial class AddEscaleraMillonariaDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("EscaleraMillonaria_API.Models.Award", b =>
                {
                    b.Property<int>("IdAward")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AwardValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryIdCategory")
                        .HasColumnType("int");

                    b.HasKey("IdAward");

                    b.HasIndex("CategoryIdCategory");

                    b.ToTable("Awards");
                });

            modelBuilder.Entity("EscaleraMillonaria_API.Models.Category", b =>
                {
                    b.Property<int>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategory");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("EscaleraMillonaria_API.Models.Player", b =>
                {
                    b.Property<int>("IdPlayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("NamePlayer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayerAwards")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayerCategory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPlayer");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("EscaleraMillonaria_API.Models.Question", b =>
                {
                    b.Property<int>("IdQuestion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CategoryIdCategory")
                        .HasColumnType("int");

                    b.Property<string>("OptionFour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionOne")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionThree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionTwo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlayerIdPlayer")
                        .HasColumnType("int");

                    b.Property<string>("QuestionStatement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdQuestion");

                    b.HasIndex("CategoryIdCategory");

                    b.HasIndex("PlayerIdPlayer");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("EscaleraMillonaria_API.Models.Award", b =>
                {
                    b.HasOne("EscaleraMillonaria_API.Models.Category", null)
                        .WithMany("Awards")
                        .HasForeignKey("CategoryIdCategory");
                });

            modelBuilder.Entity("EscaleraMillonaria_API.Models.Question", b =>
                {
                    b.HasOne("EscaleraMillonaria_API.Models.Category", null)
                        .WithMany("Questions")
                        .HasForeignKey("CategoryIdCategory");

                    b.HasOne("EscaleraMillonaria_API.Models.Player", null)
                        .WithMany("QuestionsAnsweredByPlayer")
                        .HasForeignKey("PlayerIdPlayer");
                });

            modelBuilder.Entity("EscaleraMillonaria_API.Models.Category", b =>
                {
                    b.Navigation("Awards");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("EscaleraMillonaria_API.Models.Player", b =>
                {
                    b.Navigation("QuestionsAnsweredByPlayer");
                });
#pragma warning restore 612, 618
        }
    }
}
